### ISSUE TITLE
Exception: Unexpected token p in JSON at position 4

### ISSUE THREAD

**Issue by iSumitBanik** [EdinTC/Checq#19]
If https:// or http:// is added before the website, it throws an exception as shown below.

![image](https://user-images.githubusercontent.com/36637433/64044200-dec33480-cb83-11e9-9f56-5166cac58505.png)

**Comment by Jensderond** [comment]
Thanks this is a known issue! 
We should strip everything and only use (sub domain).domain.tld

**Comment by EdinTC** [comment]
This has now been resolved and deployed.
